/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/crm': RouteRecordInfo<'/crm', '/crm', Record<never, never>, Record<never, never>>,
    '/crm/contacts': RouteRecordInfo<'/crm/contacts', '/crm/contacts', Record<never, never>, Record<never, never>>,
    '/crm/dashboard': RouteRecordInfo<'/crm/dashboard', '/crm/dashboard', Record<never, never>, Record<never, never>>,
    '/crm/leads.': RouteRecordInfo<'/crm/leads.', '/crm/leads/', Record<never, never>, Record<never, never>>,
    '/crm/notes': RouteRecordInfo<'/crm/notes', '/crm/notes', Record<never, never>, Record<never, never>>,
    '/crm/reminders': RouteRecordInfo<'/crm/reminders', '/crm/reminders', Record<never, never>, Record<never, never>>,
    '/Login': RouteRecordInfo<'/Login', '/Login', Record<never, never>, Record<never, never>>,
  }
}
